### ISSUE TITLE
Ne marche pas sous Windows

### ISSUE THREAD

**Issue by ldez** [Zenika/zen-extract-tps#7]
`zen-extract-tps trainingName`
Ne marche pas sous Windows (cmd et git bash) car il ne peut pas prendre en compte `#!/usr/bin/env node-harmony`

**Comment by Swiip** [comment]
node-harmony n'est pas une commande normale, elle est publiée avec la lib normalement... d'après mes recherches, c'est la seule façon d'avoir un auto executable avec l'option --harmony

Je veux bien un coup de main sur ce coup là, tester sous windows c'est pas pratique pour moi...

**Comment by ldez** [comment]
ok je vais regarder et tester un truc pour Windows. (Ca va surement se finir en Batch...)

**Comment by Swiip** [comment]
Regarde comment les autres npm install -g fonctionnent sous windows...

**Comment by Swiip** [comment]
Il va falloir également sortir les commandes des sources et mettre ça dans un `cli/`, c'est crado comme c'est là...
