### ISSUE TITLE
Contient des espaces insécables

### ISSUE THREAD

**Issue by ldez** [Zenika/zen-extract-tps#8]
http://jshint.com/docs/options/#nonbsp

Problème classique avec les Mac.

**Comment by Swiip** [comment]
yes, ça soule :(

**Comment by Swiip** [comment]
j'avais un plugin qui me les mettait en évidence, j'ai du le désactiver...

**Comment by ldez** [comment]
JSHint les détecte bien, j'utilise Brackets + Interactive Linter

**Comment by Swiip** [comment]
C'est vrai, j'ai récupéré l'option jshint et ça me les soulignes. (Atom + JSHint)
